'use client';

import React, { useEffect, useState } from 'react';
import { useApp } from '@/context/AppContext';

export default function ReportsPage() {
  const { currentUser, activeRole } = useApp();
  const [reportType, setReportType] = useState('inventory_valuation');
  const [dateFilter, setDateFilter] = useState(new Date().toISOString().substring(0, 10));
  const [exportMsg, setExportMsg] = useState('');
  
  const [reportData, setReportData] = useState<{ headers: string[]; rows: string[][] }>({ headers: [], rows: [] });
  const [loading, setLoading] = useState(false);
  const [invValue, setInvValue] = useState(0);

  useEffect(() => {
    fetch('/api/dashboard')
      .then(r => r.json())
      .then(json => {
        if (json?.summary?.totalInvValue) setInvValue(json.summary.totalInvValue);
      })
      .catch(() => {});
  }, []);

  useEffect(() => {
    setLoading(true);
    fetch(`/api/reports?type=${reportType}`)
      .then(r => r.json())
      .then(data => {
        if (data.headers) {
          setReportData(data);
        }
      })
      .catch(console.error)
      .finally(() => setLoading(false));
  }, [reportType]);

  const downloadBlob = (content: string, filename: string, mime: string) => {
    const blob = new Blob([content], { type: mime });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleExport = (format: 'pdf' | 'excel' | 'csv') => {
    const reportLabel = REPORT_OPTIONS.find(o => o.value === reportType)?.label || reportType;
    const { headers, rows } = reportData;
    const dateStr = new Date().toISOString().substring(0, 10);
    const meta = [
      `Report: ${reportLabel}`,
      `Generated By: ${currentUser?.fullName || ''}`,
      `Role: ${activeRole.replace(/_/g, ' ')}`,
      `Date: ${new Date().toLocaleString()}`,
      `Effective Date: ${dateFilter}`,
      '',
    ];

    if (format === 'csv') {
      const csvRows = [
        ...meta.map(m => [m]),
        headers,
        ...rows,
      ];
      const content = csvRows.map(r => r.map(c => `"${c}"`).join(',')).join('\n');
      downloadBlob(content, `NAXCUURE_${reportType.toUpperCase()}_${dateStr}.csv`, 'text/csv;charset=utf-8;');
      setExportMsg(`✓ CSV file downloaded — NAXCUURE_${reportType.toUpperCase()}_${dateStr}.csv`);

    } else if (format === 'excel') {
      const tsvRows = [
        ...meta.map(m => [m]),
        headers,
        ...rows,
      ];
      const content = tsvRows.map(r => r.join('\t')).join('\n');
      downloadBlob(content, `NAXCUURE_${reportType.toUpperCase()}_${dateStr}.xls`, 'application/vnd.ms-excel');
      setExportMsg(`✓ Excel file downloaded — NAXCUURE_${reportType.toUpperCase()}_${dateStr}.xls`);

    } else if (format === 'pdf') {
      const tableRows = rows.map(r =>
        `<tr>${r.map(c => `<td>${c}</td>`).join('')}</tr>`
      ).join('');
      const printHtml = `<!DOCTYPE html><html><head>
        <title>NAXCUURE — ${reportLabel}</title>
        <style>
          body { font-family: Arial, sans-serif; font-size: 12px; color: #0A1F3D; padding: 24px; }
          h1 { font-size: 18px; margin-bottom: 4px; }
          .sub { color: #64748B; font-size: 11px; margin-bottom: 16px; }
          .meta { margin-bottom: 20px; font-size: 11px; line-height: 1.8; }
          table { width: 100%; border-collapse: collapse; }
          th { background: #0A1F3D; color: white; padding: 8px 12px; text-align: left; font-size: 11px; }
          td { padding: 8px 12px; border-bottom: 1px solid #E2E8F0; font-size: 11px; }
          tr:nth-child(even) td { background: #F8FAFC; }
          @media print { body { padding: 0; } }
        </style>
      </head><body>
        <h1>NAXCUURE Inventory System — ${reportLabel}</h1>
        <div class="sub">Pharmaceutical Manufacturing ERP · Plant 1</div>
        <div class="meta">
          <strong>Generated by:</strong> ${currentUser?.fullName || ''} (${activeRole.replace(/_/g, ' ')})<br/>
          <strong>Report Date:</strong> ${new Date().toLocaleString()}<br/>
          <strong>Effective Date:</strong> ${new Date(dateFilter).toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' })}
        </div>
        <table>
          <thead><tr>${headers.map(h => `<th>${h}</th>`).join('')}</tr></thead>
          <tbody>${tableRows}</tbody>
        </table>
      </body></html>`;

      const w = window.open('', '_blank', 'width=900,height=700');
      if (w) {
        w.document.write(printHtml);
        w.document.close();
        w.focus();
        setTimeout(() => w.print(), 400);
      }
      setExportMsg(`✓ PDF print dialog opened — use "Save as PDF" in your browser's print menu.`);
    }

    setTimeout(() => setExportMsg(''), 5000);
  };

  const REPORT_OPTIONS = [
    { value: 'inventory_valuation', label: 'Stores Asset Valuation' },
    { value: 'discrepancy_ledger', label: 'Stock Discrepancy Ledger' },
    { value: 'department_consumption', label: 'Department Consumption' },
    { value: 'vendor_compliance', label: 'Vendor Quality & Ratings' },
    { value: 'downtime_analysis', label: 'Downtime Analysis (MTTR/MTBF)' },
  ];

  return (
    <div>
      <div className="flex-space mb-4">
        <div>
          <h2 className="page-title">Operational Reporting & Analytics</h2>
          <p className="text-muted">Generate filtered reports and export summaries for executive monitoring.</p>
        </div>
      </div>

      {exportMsg && (
        <div className="nax-success-box mb-4">{exportMsg}</div>
      )}

      <div style={{ display: 'grid', gridTemplateColumns: '260px 1fr', gap: '20px', alignItems: 'flex-start' }}>
        {/* Filter Sidebar */}
        <div style={{
          background: 'white',
          border: '1px solid #E2E8F0',
          borderRadius: '16px',
          overflow: 'hidden',
          boxShadow: '0 2px 8px rgba(0,0,0,0.04)',
        }}>
          <div style={{
            padding: '16px 20px',
            borderBottom: '1px solid #F1F5F9',
            background: '#FAFBFC',
          }}>
            <h4 style={{ fontSize: '0.9rem', fontWeight: 700, color: '#0A1F3D' }}>Configure Report</h4>
          </div>
          <div style={{ padding: '20px', display: 'flex', flexDirection: 'column', gap: '16px' }}>
            <div className="form-group">
              <label>Report Module</label>
              <select className="form-control" value={reportType} onChange={(e) => setReportType(e.target.value)}>
                {REPORT_OPTIONS.map(opt => (
                  <option key={opt.value} value={opt.value}>{opt.label}</option>
                ))}
              </select>
            </div>

            <div className="form-group">
              <label>Effective Date</label>
              <input
                type="date"
                className="form-control"
                value={dateFilter}
                onChange={(e) => setDateFilter(e.target.value)}
              />
            </div>

            <div style={{ borderTop: '1px solid #F1F5F9', paddingTop: '16px', display: 'flex', flexDirection: 'column', gap: '8px' }}>
              <button id="export-csv" className="btn btn-primary btn-sm" onClick={() => handleExport('csv')}>
                <svg fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" style={{ width: 13, height: 13 }}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75V16.5M16.5 12 12 16.5m0 0L7.5 12m4.5 4.5V3" />
                </svg>
                Export CSV
              </button>
              <button id="export-excel" className="btn btn-blue btn-sm" onClick={() => handleExport('excel')}>
                <svg fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" style={{ width: 13, height: 13 }}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 0 0-3.375-3.375h-1.5A1.125 1.125 0 0 1 13.5 7.125v-1.5A3.375 3.375 0 0 0 10.125 2.25H8.25m0 12.75h7.5m-7.5 3H12M10.5 2.25H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 0 0-9-9Z" />
                </svg>
                Export Excel
              </button>
              <button id="export-pdf" className="btn btn-secondary btn-sm" onClick={() => handleExport('pdf')}>
                <svg fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" style={{ width: 13, height: 13 }}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M6.72 13.829c-.24.03-.48.062-.72.096m.72-.096a42.415 42.415 0 0 1 10.56 0m-10.56 0L6.34 18m10.94-4.171c.24.03.48.062.72.096m-.72-.096L17.66 18m0 0 .229 2.523a1.125 1.125 0 0 1-1.12 1.227H7.231c-.662 0-1.18-.568-1.12-1.227L6.34 18m11.318 0h1.091A2.25 2.25 0 0 0 21 15.75V9.456c0-1.081-.768-2.015-1.837-2.175a48.055 48.055 0 0 0-1.913-.247M6.34 18H5.25A2.25 2.25 0 0 1 3 15.75V9.456c0-1.081.768-2.015 1.837-2.175a48.056 48.056 0 0 1 1.913-.247m10.5 0a48.536 48.536 0 0 0-10.5 0m10.5 0V3.375c0-.621-.504-1.125-1.125-1.125h-8.25c-.621 0-1.125.504-1.125 1.125v3.659M18 10.5h.008v.008H18V10.5Zm-3 0h.008v.008H15V10.5Z" />
                </svg>
                Export PDF
              </button>
            </div>

            {/* Metadata */}
            <div style={{ borderTop: '1px solid #F1F5F9', paddingTop: '14px' }}>
              <div style={{ fontSize: '0.7rem', color: '#94A3B8', lineHeight: 1.7 }}>
                <div>Generated by: <strong style={{ color: '#475569' }}>{currentUser?.fullName}</strong></div>
                <div>Role: <strong style={{ color: '#475569' }}>{activeRole.replace(/_/g, ' ')}</strong></div>
                <div>Date: <strong style={{ color: '#475569' }}>{new Date().toLocaleDateString()}</strong></div>
              </div>
            </div>
          </div>
        </div>

        {/* Report Preview */}
        <div className="table-container" style={{ margin: 0 }}>
          <div className="table-header-bar">
            <div>
              <h3>{REPORT_OPTIONS.find(o => o.value === reportType)?.label || 'Report'}</h3>
              <p style={{ fontSize: '0.75rem', color: '#94A3B8', marginTop: '2px' }}>
                As of: {new Date(dateFilter).toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' })}
              </p>
            </div>
            <span className="status-badge approved">Live Data</span>
          </div>

          <div className="nax-table-wrapper" style={{ minHeight: '300px', position: 'relative' }}>
            {loading ? (
               <div className="loading-center"><div className="spinner" /></div>
            ) : reportData.rows.length === 0 ? (
               <div style={{ padding: '40px', textAlign: 'center', color: '#64748B' }}>No data found for this report.</div>
            ) : (
              <table className="nax-table">
                <thead>
                  <tr>
                    {reportData.headers.map((h, i) => <th key={i}>{h}</th>)}
                  </tr>
                </thead>
                <tbody>
                  {reportData.rows.map((row, i) => (
                    <tr key={i} style={row.includes('TOTAL ASSET VALUE') ? { background: '#F8FAFC', fontWeight: 600 } : {}}>
                      {row.map((cell, j) => (
                        <td key={j} className={cell.startsWith('NAX-') ? 'code-text' : (cell.startsWith('$') ? 'text-bold' : '')} style={cell.startsWith('$') && row.includes('TOTAL ASSET VALUE') ? { color: '#059669', fontWeight: 800 } : {}}>
                          {cell}
                        </td>
                      ))}
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
